install.packages("dplyr")
install.packages("readr")
library(dplyr)
library(readr)
cars <- read_csv("C:/Users/DELL/Desktop/siya/Cleaned_Car_Price_Prediction.csv")
head(cars)
high_price_cars <- subset(cars, price > 50000)
cat("Cars with price > 50000:", nrow(high_price_cars), "\n")
summary(high_price_cars$price)
low_mileage_high_price <- subset(cars, price > 50000 & mileage < 80000)
cat("Low mileage + high price cars:", nrow(low_mileage_high_price), "\n")
head(low_mileage_high_price)
diesel_or_electric <- subset(cars, fuel_type == "Diesel" | fuel_type == "Electric")
cat("Diesel or Electric cars:", nrow(diesel_or_electric), "\n")
head(diesel_or_electric)
large_engine_cars <- cars |>
  filter(engine_size > 4.0)
cat("Cars with engine size > 4.0:", nrow(large_engine_cars), "\n")
summary(large_engine_cars$engine_size)
new_automatic <- cars |>
  filter(transmission == "Automatic", condition == "New")
cat("New + Automatic cars:", nrow(new_automatic), "\n")
head(new_automatic)
premium_brands <- cars |>
  filter(brand %in% c("BMW", "Audi", "Tesla"))
cat("Premium brand cars:", nrow(premium_brands), "\n")
table(premium_brands$brand)
