library(dplyr)
library(readr)
df1 <- read_csv("C:/Users/itlab/OneDrive/Documents/S105/Cleaned_BMW_Sales_Data.csv")
df2 <- read_csv("C:/Users/itlab/OneDrive/Documents/S105/Cleaned_Car_Price_Prediction.csv")
keys <- c("model", "year", "fuel_type", "transmission")
df1 <- df1 %>% mutate(across(all_of(keys), as.character))
df2 <- df2 %>% mutate(across(all_of(keys), as.character))
merged_inner <- inner_join(df1, df2, by = keys)
merged_left <- left_join(df1, df2, by = keys)
merged_full <- full_join(df1, df2, by = keys)
appended <- bind_rows(df1, df2)
cat("Rows in df1:", nrow(df1), "\n")
cat("Rows in df2:", nrow(df2), "\n")
cat("Rows in merged_inner:", nrow(merged_inner), "\n")
cat("Rows in merged_left:", nrow(merged_left), "\n")
cat("Rows in merged_full:", nrow(merged_full), "\n")
cat("Rows in appended:", nrow(appended), "\n")
write_csv(merged_inner, "merged_inner.csv")
write_csv(merged_left,  "merged_left.csv")
write_csv(merged_full,  "merged_full.csv")
write_csv(appended,     "appended_rows.csv")
cat("Rows in inner join:", nrow(merged_inner), "\n")
cat("Rows in left join:", nrow(merged_left), "\n")
cat("Rows in full join:", nrow(merged_full), "\n")
cat("Rows in appended:", nrow(appended), "\n")
